### ISSUE TITLE
Set CNAME record with Cornell IT

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#133]
Requesting access to mycourseindex.cis.cornell.edu and mci.cis.cornell.edu

**Comment by bayoumi17m** [comment]
IT ticket has been submitted. We are now waiting for a response.

**Comment by oscarso2000** [comment]
i see that mci.cornell.cis.edu ;)

**Comment by oscarso2000** [comment]
would this mean our EC2 instance will not run on our www.mycourseindex.com website anymore and cornell will be paying and hosting?

**Comment by bayoumi17m** [comment]
No, all the CNAME (Canonical Name) record does is point those web addresses to our server! So people can go to mci.cis.cornell.edu, mycourseindex.cis.cornell.edu, or mycourseindex.com and they all go to the same place!

This helps with branding  / image since it seems like a much more professional service being set up by Cornell IT (specifically COECIS IT) and is just cool to say I guess.

**Comment by bayoumi17m** [comment]
A corresponding PR has been drafted. We are waiting for completion by COECIS IT (Network team) for receipt of completion.
