### ISSUE TITLE
Set up "single-click" / email sign up for professors

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#134]
Allow upload of CSV (netid) for students authorized, sending of Piazza course id (it is sometimes called a network ID on the JSON RPC that Piazza runs), and enrolling in Canvas.

This method must allow the professors an almost seamless setup so that they have the minimal work and we don't have to redo the same steps for every single class and every semester that we have to do this.

**Comment by oscarso2000** [comment]
If we could develop a process where we allow professors to click "i accept" on agreements and stuff, we could streamline automatically create bots, scrape their piazza and other stuff, that'd be cool but i think it's on another level.

**Comment by bayoumi17m** [comment]
This is actually what we want to do and that's why it's high priority actually. Essentially, we need to have an email + bot set up with hooks (or some other mechanism) that after express authorization / sign up does all of this stuff for us.

A convenient method is sending an email with a box link (FERPA compliant), which we can then download. With a little bit of selenium (headless web driver, but again not the only way) and some ingenuity, this can totally be done.

**Comment by TrueshotBarrage** [comment]
Just jotting down for clarity:
- Box link to verify users w/ access. Includes CSV link with enrollment information. 
- CSV has NetID, access
- Allow for Canvas/other course website link input
