### ISSUE TITLE
Review Kube deployment

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#136]
Review the current deployment documentation, Terraform (what it is and how we use it), Kubernetes, CI/CD platform + structure, and docker!

**Comment by bayoumi17m** [comment]
@ngjulia @TrueshotBarrage @John @oscarso2000 Are any of you interested in Kubernetes / Deployment?

**Comment by TrueshotBarrage** [comment]
Sure sounds fun

**Comment by ngjulia** [comment]
Me too!

**Comment by oscarso2000** [comment]
Down!
