### ISSUE TITLE
Result Outline fails to display

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#138]
If you look on the right, the outline card is not showing up which is an issue since the user has no way to get a preview or link to the actual document.
<img width="1436" alt="Screen Shot 2020-09-17 at 9 48 42 PM" src="https://user-images.githubusercontent.com/28033539/93546101-16885000-f930-11ea-9f19-bc3ca9907131.png">

Here is the HTML being sent and we can see that the outline is there but it isn't showing and I haven't looked into why.
<img width="720" alt="Screen Shot 2020-09-17 at 9 52 03 PM" src="https://user-images.githubusercontent.com/28033539/93546099-16885000-f930-11ea-8f44-6ba8e0fa7350.png">

**Comment by oscarso2000** [comment]
<img width="1440" alt="Screen Shot 2020-09-18 at 12 40 09 AM" src="https://user-images.githubusercontent.com/20172573/93556808-92da5d80-f947-11ea-88cf-cc420aa465d7.png">
it works?

**Comment by oscarso2000** [comment]
need to check issue with instance instead then. it's probably not code

**Comment by bayoumi17m** [comment]
@oscarso2000 Look at the inspect above, the outline class is actually grayed out which means the code was not displaying. In general this does not occur, it only happened to me today however we need to see if this is reproducible and under what conditions it does occur.
