### ISSUE TITLE
Jinja Security Considerations

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#3]
@oscarso2000 
https://github.com/oscarso2000/Piazza/blob/89d2ac1f938f45054fad1307bba08ef05c6e6ee5/app/templates/_formhelpers.html#L1-L12

This seems to use Jinja2 templates. This isn't bad BUT there are security considerations with this. I don't think we will have trolls that try to do anything but it is something to keep in mind. We may want to abstract the frontend from the backend.

Here are some of the issues:
https://snyk.io/vuln/pip:jinja2
https://flask.palletsprojects.com/en/1.1.x/security/

**Comment by oscarso2000** [comment]
fixed with using react.js + flask instead of jinja.
