### ISSUE TITLE
Auto-Update Piazza Posts

### ISSUE THREAD

**Issue by bayoumi17m** [oscarso2000/MyCourseIndex#54]
Create a module / application that:
- On startup, download all JSON files (or whatever format) from Amazon S3
- Using Piazza-API download all new Piazza posts
    - NOTE: DO NOT COMMIT YOUR PASSWORD
    - Use a cfg file
- Preprocess all of these new Piazza posts
- Add to data structure containing all the other posts
- Recompute TFIDF, postings, etc
- Upload all data structures to Amazon S3

**Comment by bayoumi17m** [comment]
Look into using websockets with Piazza as then Piazza will notify us every time there is an update and we will be realtime updating that data.

**Comment by oscarso2000** [comment]
script has been written to load data. not yet at auto loading stage
